# Generated by Django 4.1.6 on 2023-03-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HBAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customeroderdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobilenumber', models.CharField(max_length=13)),
                ('totalamount', models.IntegerField(default=0)),
                ('delivery_type', models.CharField(max_length=100)),
                ('addcoupons', models.CharField(max_length=100)),
                ('ordedatetime', models.CharField(max_length=100)),
                ('status', models.CharField(default='new oder', max_length=122)),
                ('accepted_date_time', models.CharField(max_length=100)),
                ('accepted_by', models.CharField(default=0, max_length=100)),
                ('Regicted_by', models.CharField(default=0, max_length=100)),
                ('Recevied_by', models.CharField(default=0, max_length=100)),
                ('completedstatus', models.CharField(default=0, max_length=100)),
                ('delivery_by_id', models.CharField(default=0, max_length=100)),
            ],
        ),
    ]
