# Generated by Django 4.1.6 on 2023-03-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HBAPP', '0003_customeroderdetails_hotelid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemorderdetails',
            old_name='gstnumber',
            new_name='hotelid',
        ),
    ]
